### ISSUE TITLE
Naming consistency

### ISSUE THREAD

**Issue by navaru** [valvic66/conditional#1]
https://github.com/valvic66/conditional/blob/6b58743f338c45c59096a44d9139c4f960426423/source/Btn/index.js#L24

Avoid using name shortcuts: 
- `btn` => `button`
- `getBtnCSSClasses` => `getCSSClasses`

**Comment by valvic66** [comment]
- btn replaced with button and <Button />
- getButtonCSSClasses replaced with getCSSClasses and getLabelCSSClasses
Thanks a lot.

**Comment by valvic66** [comment]
- btn replaced with button and Btn in component name with Button

- getButtonCSSClasses replaced with getCSSClasses and getLabelCSSClasses

Thanks a lot.
