### ISSUE TITLE
JS destructuring

### ISSUE THREAD

**Issue by navaru** [valvic66/conditional#2]
For better readability the code can be written as:

https://github.com/valvic66/conditional/blob/6b58743f338c45c59096a44d9139c4f960426423/source/index.js#L45-L47

```
const { options, itemsPerSlide, slideIndex } = this.state
```

---

https://github.com/valvic66/conditional/blob/6b58743f338c45c59096a44d9139c4f960426423/source/index.js#L39-L41

```
    this.setState({ slideIndex })
```

**Comment by valvic66** [comment]
- Regarding the first issue:
The values come from the props and not from the state:
const options = this.props.options || []
const itemsPerSlide = this.props.itemsPerSlide
Changed to: 
const {options, itemsPerSlide} = this.props

- Second readability issue fixed

Thanks a lot.
